[package]
name = "vectors"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg11 = ["pgrx/pg11", "pgrx-tests/pg11"]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg_test = []

[dependencies]
pgrx = { git = "https://github.com/tensorchord/pgrx.git", rev = "76c470f2f10c8d54dd0f6eb659d74c65ff0ba537" }
openai_api_rust = "0.1.8"
static_assertions = "1.1.0"
libc = "0.2.146"
serde = "1.0.163"
bincode = "1.3.3"
rand = "0.8.5"
byteorder = "1.4.3"
crc32fast = "1.3.2"
log = "0.4.18"
env_logger = "0.10.0"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
dashmap = "5.4.0"
parking_lot = "0.12.1"
memoffset = "0.9.0"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.40"
anyhow = "1.0.71"
async-channel = "1.8.0"
ordered-float = { version = "3.7.0", features = ["serde"] }
bitvec = "1.0.1"
memmap = "0.7.0"

[dev-dependencies]
pgrx-tests = { git = "https://github.com/tensorchord/pgrx.git", rev = "76c470f2f10c8d54dd0f6eb659d74c65ff0ba537" }
httpmock = "0.6"
mockall = "0.11.4"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true
