name: Rust check

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Format check
      run: cargo fmt --check
      
  build:
    strategy:
      matrix:
        version: [15]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Postgres
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y install libpq-dev postgresql-${{ matrix.version }} postgresql-server-dev-${{ matrix.version }}
    - name: Set up pgrx
      run: |
        cargo install cargo-pgrx --version 0.10.0-beta.1
        cargo pgrx init --pg${{ matrix.version }}=/usr/lib/postgresql/${{ matrix.version }}/bin/pg_config
    - name: Build
      run: cargo build --verbose
    - name: Semantic check
      run: cargo clippy
    - name: Test
      env:
        RUST_BACKTRACE: 1
      run: cargo test --all --no-default-features --features "pg${{ matrix.version }} pg_test" -- --nocapture
