name: Release on Publish

on:
  release:
    types:
      - created
      - edited

permissions:
  actions: write
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          TAG="${{ github.event.release.tag_name }}"
          SEMVER=${TAG:1}
          gh workflow run release.yml -r v$SEMVER -f version=$SEMVER
        env:
          GH_TOKEN: ${{ github.token }}
