name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 1
